version: "3.6"

services:

  app:
    build:
      context: docker/app
      args:
        - USER_ID=${USER_ID:-1000}
        - USER_NAME=${USER_NAME:-default}
    container_name: baj_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/app/local-cli.ini:/etc/php/7.0/cli/conf.d/99-overrides.ini
      - ./docker/app/local-fpm.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      - ./docker/app/pool.conf:/etc/php/7.0/fpm/pool.d/z-overrides.conf
      - sock-app:/run/php
      - sock-db:/run/mysqld

  web:
    image: nginx:alpine
    container_name: baj_web
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/tls:/etc/nginx/tls
      - sock-app:/run/php
    ports:
      - "${WEB_PORT:-443}:443"
      - "${WEB_PORT_H1:-80}:80"

  db:
    image: mysql:5.6
    container_name: baj_db
    volumes:
      - db:/var/lib/mysql
      - sock-db:/run/mysqld
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  cache:
    image: redis:alpine
    container_name: baj_cache
    ports:
      - "${CACHE_PORT:-6379}:6379"

  stripe:
    image: stripemock/stripe-mock
    container_name: baj_stripe

volumes:
  db:
  sock-db:
  sock-app:
